---

- debug: var=aws_kms_keys
#- command: /usr/bin/false

- include_tasks: pre.yml

- command: /usr/bin/false

- include_tasks: create.yml
  with_items: '{{ _aws_kms_configured_key_aliases }}'
  when: _aws_kms_key_alias not in _aws_kms_existing_key_aliases
  loop_control:
    loop_var: _aws_kms_key_alias

- include_tasks: sync_policy.yml
  with_items: '{{ _aws_kms_configured_key_aliases }}'
  when: >
    _aws_kms_key_alias in _aws_kms_configured_key_aliases and
    _aws_kms_key_alias in _aws_kms_existing_key_aliases
  loop_control:
    loop_var: _aws_kms_key_alias

- include_tasks: post.yml
